GRANT SELECT ON CURRICUL.REG_CURRICULAR TO WSARM01; 
GRANT SELECT ON MATRICUL.REG_HABILITAC TO WSARM01; 
GRANT EXECUTE ON TRAMITES.SP_CUMPLE_REQUISITOS_ASP TO WSARM01;
GRANT ALL ON MATRICUL.AUTORIZ_CURSO TO WSARM01;
GRANT SELECT ON MATRICUL.AUTORIZ_ALUM TO WSARM01;
GRANT EXECUTE ON CURRICUL.PQ_CUMPLIMIENTO1 TO WSARM01;--SE DA CON TODO Y PAQUETE POR QUE LA FUNCION ESTA DENTRO SF_CALCULA_VEZ_CURSO
COMMIT;
