-- Create table
create table WFW_CARRERA_OPCIONES
(
    carrera_opc_id          NUMBER(10) NOT NULL,
    tipo_solicitud_mod_id   NUMBER(10) NOT NULL,
    cod_producto            CHAR(8) NOT NULL,
    excluir_flujo           NUMBER(1) DEFAULT 0 NOT NULL,
    comentario              VARCHAR2(500),
    usuario_crea            VARCHAR2(10) NOT NULL,
    fecha_crea              DATE NOT NULL,
    usuario_mod             VARCHAR2(10),
    fecha_mod               DATE
);
ALTER TABLE wfw_carrera_opciones ADD CHECK (excluir_flujo IN (0, 1));
/*
tablespace WSPWORK_DATA
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );*/
-- Add comments to the columns 
COMMENT ON COLUMN wfw_carrera_opciones.carrera_opc_id IS 'ID DE LA TABLA';
COMMENT ON COLUMN wfw_carrera_opciones.tipo_solicitud_mod_id IS 'C�DIGO DEL TIPO DE SOLICITUD MODALIDAD';
COMMENT ON COLUMN wfw_carrera_opciones.cod_producto IS 'C�DIGO DEL PRODUCTO';
COMMENT ON COLUMN wfw_carrera_opciones.excluir_flujo IS 'FLAG PARA EXCLUIR DEL FLUJO DEL TR�MITE';
COMMENT ON COLUMN wfw_carrera_opciones.comentario IS 'COMENTARIO';
COMMENT ON COLUMN wfw_carrera_opciones.usuario_crea IS 'USUARIO DE CREACI�N';
COMMENT ON COLUMN wfw_carrera_opciones.fecha_crea IS 'FECHA DE CREACI�N';
COMMENT ON COLUMN wfw_carrera_opciones.usuario_mod IS 'USUARIO DE ACTUALIZACI�N';
COMMENT ON COLUMN wfw_carrera_opciones.fecha_mod IS 'FECHA DE ACTUALIZACI�N';
-- Create/Recreate primary, unique and foreign key constraints 
alter table WFW_CARRERA_OPCIONES
  add constraint PK_CARRERA_OPCIONES primary key (CARRERA_OPC_ID);
alter table WFW_CARRERA_OPCIONES
  add constraint UK_CARRERA_OPCIONES_01 unique (COD_PRODUCTO, TIPO_SOLICITUD_MOD_ID);
alter table WFW_CARRERA_OPCIONES
  add constraint FK_CARRERA_OPCIONES_01 foreign key (TIPO_SOLICITUD_MOD_ID)
  references wfw_tipo_solicitud_mod (TIPO_SOLICITUD_MOD_ID);

commit;

CREATE SEQUENCE WFWSQ_CARRRERA_OPCIONES
MINVALUE 1
MAXVALUE 9999999999999999999999999999
START WITH 12
INCREMENT BY 1
NOCACHE
NOCYCLE;

commit;

INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (3,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310373',1,'La carrera seleccionada requiere de una entrevista previa con la Dirección de carrera.','CARAUCO',sysdate);
INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (4,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310492',1,'La carrera seleccionada requiere de una entrevista previa con la Dirección de carrera.','CARAUCO',sysdate);
INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (5,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310344',1,'La carrera seleccionada presenta especialidades. Realice su solicitud a través de Contacto Web.','CARAUCO',sysdate);
INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (6,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310409',1,'La carrera seleccionada presenta especialidades. Realice su solicitud a través de Contacto Web.','CARAUCO',sysdate);
INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (7,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310005',1,'Para llevar cursos de la carrera seleccionada, previamente deberás realizar el trámite de Traslado Interno.','CARAUCO',sysdate);
INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (8,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310582',1,'La carrera seleccionada corresponde a otra modalidad. Para mayor información, realice su solicitud a través de Contacto Web. ','CARAUCO',sysdate);
INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (9,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310581',1,'La carrera seleccionada corresponde a otra modalidad. Para mayor información, realice su solicitud a través de Contacto Web. ','CARAUCO',sysdate);
INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (10,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310583',1,'La carrera seleccionada corresponde a otra modalidad. Para mayor información, realice su solicitud a través de Contacto Web. ','CARAUCO',sysdate);
INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (11,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310584',1,'La carrera seleccionada corresponde a otra modalidad. Para mayor información, realice su solicitud a través de Contacto Web.','CARAUCO',sysdate);
INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (1,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310429',1,'La carrera seleccionada requiere de una entrevista previa con la Dirección de carrera.','CARAUCO',sysdate);
INSERT INTO WFW_CARRERA_OPCIONES (CARRERA_OPC_ID,TIPO_SOLICITUD_MOD_ID,COD_PRODUCTO,EXCLUIR_FLUJO,COMENTARIO,USUARIO_CREA,FECHA_CREA) VALUES (2,(SELECT TIPO_SOLICITUD_MOD_ID FROM WFW_TIPO_SOLICITUD_MOD WHERE COD_MODAL_ESTUDIO = 'AC' AND COD_LINEA_NEGOCIO = 'U'  AND TIPO_SOLICITUD_ID IN (SELECT TIPO_SOLICITUD_ID FROM WFW_TIPO_SOLICITUD WHERE COD_TIPO_SOL = 'MAOC')),'3310466',1,'La carrera seleccionada requiere de una entrevista previa con la Dirección de carrera.','CARAUCO',sysdate);

commit;