REVOKE SELECT ON CURRICUL.REG_CURRICULAR FROM WSARM01; 
REVOKE SELECT ON MATRICUL.REG_HABILITAC FROM WSARM01; 
REVOKE EXECUTE ON TRAMITES.SP_CUMPLE_REQUISITOS_ASP FROM WSARM01;
REVOKE ALL ON MATRICUL.AUTORIZ_CURSO FROM WSARM01;
REVOKE SELECT ON MATRICUL.AUTORIZ_ALUM FROM WSARM01;
REVOKE EXECUTE ON CURRICUL.PQ_CUMPLIMIENTO1 FROM WSARM01;
COMMIT;
